apiVersion: batch/v1
kind: Job

metadata:
  name: proxysql-sync

spec:
  template:
    spec:
      activeDeadlineSeconds: 3600
      containers:
        - name: proxysql-sync
          image: "1.0.4"
          imagePullPolicy: Never
          args: ["--sync"]

          volumeMounts:
            - mountPath: /etc/proxysql.cnf
              name: proxysql
              subPath: proxysql.cnf

      volumes:

        - name: proxysql
          configMap:
            name: proxysql
            defaultMode: 0777

      restartPolicy: Never