apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: proxysql
  labels:
    app: proxysql

spec:
  replicas: 3
  serviceName: proxysql

  updateStrategy:
    type: OnDelete

  selector:
    matchLabels:
      app: proxysql

  template:
    metadata:
      labels:
        app: proxysql

    spec:
      restartPolicy: Always
      containers:
        - image: "scienta/k8s-proxysql-cluster:branch-0.1"
          name: proxysql
          imagePullPolicy: Always

          ports:
            - containerPort: 6033
              name: proxysql-mysql
            - containerPort: 6032
              name: proxysql-admin

          readinessProbe:
            initialDelaySeconds: 1
            periodSeconds: 1

            exec:
              command:
                - cat
                - /proxysql-ready

          args: [ "--cluster" ]

          volumeMounts:
            - mountPath: /etc/proxysql.cnf
              name: proxysql
              subPath: proxysql.cnf

      volumes:

        - name: proxysql
          configMap:
            name: proxysql
            defaultMode: 0777
